<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    
    <PropertyGroup>
        <IsPackable>true</IsPackable>
        <PackageId>Pingen.Client</PackageId>
        <Authors>Maximilian Hollnbuchner</Authors>
        <Company>weboost.at</Company>
        <Description>.NET client for the Pingen API.</Description>
        <PackageTags>pingen;api-client;letters;print</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageProjectUrl>https://github.com/weboost-at/Pingen.Client</PackageProjectUrl>
        <RepositoryUrl>https://github.com/weboost-at/Pingen.Client</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>
        <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
        <Deterministic>true</Deterministic>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="MinVer" Version="7.0.0" PrivateAssets="all" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
    </ItemGroup>

</Project>
