name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - run: dotnet restore ./src/Pingen.Client/Pingen.Client.sln
      - run: dotnet build -c Release --no-restore ./src/Pingen.Client/Pingen.Client.sln
      - run: dotnet test -c Release --no-build ./src/Pingen.Client/Pingen.Client.sln
      - run: dotnet pack -c Release --no-build -o artifacts ./src/Pingen.Client/Pingen.Client.sln

      - uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: artifacts/*

      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push
        run: >
          dotnet nuget push "artifacts/*.nupkg"
          --api-key ${{ steps.login.outputs.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
          --skip-duplicate